sudo: required

language: python

python:
  - "3.5"
  - "3.6"

env:
  - DOCKER_VERSION=17.03
  - DOCKER_VERSION=17.04
  - DOCKER_VERSION=17.05
  - DOCKER_VERSION=17.06

services:
  - docker

install:
  - docker run -d --privileged --net host --name ci-docker docker:$DOCKER_VERSION-dind dockerd -H tcp://localhost:27015
  - docker run -d --name registry -p 5000:5000 registry
  - docker run -d -p 5001:5001 --name registry2 -v `pwd`/tests/certs:/certs -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/certs/htpasswd -e REGISTRY_HTTP_ADDR=0.0.0.0:5001 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt -e REGISTRY_HTTP_TLS_KEY=/certs/registry.key registry:2
  - pip install -r requirements/ci.txt

script:
  - python setup.py check -rms
  - DOCKER_HOST=tcp://localhost:27015 tox

after_success:
  - codecov

jobs:
  include:
    - stage: deploy
      python: 3.6
      deploy:
        provider: pypi
        user: barrachri
        password:
          secure: eb2IT0ciAuoW3jltLcnNcLQHU9RmXxu49j0G51W0Ke5NgSFez9yYAlVm6qvH1ZZaTEKaON3fckHpZGqUsMPGh0FXVRR/4zLwqHz0z/00aCnsB5gzpzSG3NMxSZJ3o4AzHlcu3d+pp8pTNGbz5tu3hKZLVscr1gWAh+Apt75P/8ZWVx7G4D6oreFWlMkKq8b7brKlx8j33f9Hf4X2rhqv5AKeJiYdGU5EEz926f1/aVgk4iaoIj2ML5dd+joJyUmWLAsmlRuIqq0jZ5KE+5Wm8S4SsZNhjZ2MZJlfl38W7eMySni0Xqclb24irpsY/06gW7oDoIrF3UQb4ZJXiSvcT9hzCQFBazArgcpM0ugJlv13xQ5Ll2dEpGF3ko2/32zHu+82GrqMqttmgZmHEywU/uJiujyXsnNhFJmoB/QZgFuFqO5haMiJ7uERnLv+JQDSzt8K01t5xYiPFS7Ov8vx0eO8qLbNQISj+y/s0b0AeYKxoX9VVOtzBwUfOuDBtrdDGtzmIM6MAvZjmJHEUY3PC6SkofKxsr8AayVzgZHkqaZiH0q+FsJ9Z+dmCWw9gEd3CWy0iGDudv7yPdE+iBJlbdHWzVYZOC0ZmA3z7kdPkqJjEGqc8WUQRVafgH0HTViy4EYdXDl2wXlHN95ayhM6i2k+yg/FF2YS7AWojwc0o2w=
        distributions: sdist bdist_wheel
        on:
          tags: true
          all_branches: true
