version: '2'
services:
  aiodocker:
    build: .
    depends_on:
      - docker
      - registry
    volumes:
      - ".:/usr/src/aiodocker"
    environment:
      DOCKER_HOST: "http://docker:2375"
      DOCKER_REGISTRY: "registry:5000"
    command: ./run-tests-in-docker.sh
  docker:
    image: docker:dind
    privileged: true
    command: "--insecure-registry registry:5000"
    depends_on:
      - registry
  registry:
    image: registry
