version: '2'
services:
  aiodocker:
    build: .
    links:
      - docker
      - registry
    volumes:
      - "./:/usr/src/aiodocker"
    environment:
      DOCKER_HOST: "http://docker:2375"
      DOCKER_REGISTRY: "registry:5000"
    command: py.test
  docker:
    image: docker
    command: "--insecure-registry registry:5000"
  registry:
    image: registry
